baseURL = "https://blog.learney.io/"
languageCode = "en-us"
title = "Learney Blog - Knowledge aggregator for developers"
theme = "onepress"
publishDir = "docs"
widgets = false
config = "config.toml"
googleAnalytics = "UA-131215004-2"
canonifyURLS = true
disqusShortname = "learney-1"

[params]
    customCSS = true
    readMore = "Read more"
    enableRSS = true
    logo = "/images/brand/logo_blue.png"
    twitter = "https://twitter.com/learneyapp"
    opengraphImage = "images/posts/learney_og.jpg"
    facebook = "http://facebook.com/learneyapp"
    shareButton = true