baseURL = "https://blog.learney.io/"
languageCode = "en-us"
title = "Learney Blog - Knowledge aggregator for developers"
theme = "onepress"
publishDir = "docs"
widgets = false
config = "config.toml"
googleAnalytics = "UA-131215004-2"
canonifyURLS = true

[params]
    customCSS = true
    readMore = "Read more"
    logo = "/images/brand/logo_blue.png"
    twitter = "@psmyrdek"
    opengraphImage = "images/posts/learney_og.jpg"